apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pod.yaml
  - pvc.yaml
  - svc.yaml
  - tkc.yaml

namespace: tanzu-quickstart

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: vsphere-with-tanzu-quick-start

# users can `kubectl apply -k manifests/` to apply with the demo namespace and labels
