apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vsphere-with-tanzu-pv
  namespace: tanzu-quickstart
  labels:
    app: nginx
    role: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: kubernetes-demo-storage