apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc-1
```yaml
apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc-1
  namespace: tanzu-quickstart
  labels:
    role: demo
spec:
  distribution:
    version: v1.18
  topology:
    controlPlane:
      class: guaranteed-small
      count: 1
      storageClass: kubernetes-demo-storage
    workers:
      class: guaranteed-small
      count: 1
      storageClass: kubernetes-demo-storage
  settings:
    storage:
      classes: ["kubernetes-demo-storage"]              #Named PVC storage classes
      defaultClass: kubernetes-demo-storage                     #Default PVC storage class